version: '2'

services:
  postgresql:
    image: library/postgres:latest
    labels:
      kompose.volume.size: 1Gi
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    environment: 
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=openscp_forum
  redis:
    image: frodenas/redis:latest
    labels:
      kompose.volume.size: 1Gi
    environment:
      - REDIS_PASSWORD=${REDIS_PW}
    volumes:
      - ./redis:/data
  discourse:
    image: bitnami/discourse:latest
    labels:
      kompose.volume.size: 1Gi
    ports:
      - 3000:3000
    volumes:
      - ./discourse:/bitnami
    depends_on:
      - postgresql
      - redis
    environment: 
      - DISCOURSE_USERNAME=admin
      - DISCOURSE_PASSWORD=discourse_admin_password
      - DISCOURSE_EMAIL=${DISCOURSE_EMAIL}
      - DISCOURSE_SITENAME=${DISCOURSE_SITENAME}
      - POSTGRESQL_ROOT_USER=postgres
      - POSTGRESQL_ROOT_PASSWORD=${POSTGRES_PW}
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_PORT_NUMBER=5432
      - DISCOURSE_POSTGRESQL_USERNAME=postgres
      - DISCOURSE_POSTGRESQL_PASSWORD=${POSTGRES_PW}
      - DISCOURSE_POSTGRESQL_NAME=openscp_forum
      - REDIS_HOST=redis
      - REDIS_PORT_NUMBER=6379
      - REDIS_PASSWORD=${REDIS_PW}
  sidekiq:
    image: bitnami/discourse:latest
    labels:
      kompose.volume.size: 1Gi
    depends_on:
      - discourse
    volumes:
      - ./sidekiq:/bitnami
    command: nami start --foreground discourse-sidekiq
    environment: 
      - DISCOURSE_USERNAME=admin
      - DISCOURSE_PASSWORD=discourse_admin_password
      - DISCOURSE_EMAIL=${DISCOURSE_EMAIL}
      - DISCOURSE_SITENAME=${DISCOURSE_SITENAME}
      - POSTGRESQL_ROOT_USER=postgres
      - POSTGRESQL_ROOT_PASSWORD=${POSTGRES_PW}
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_PORT_NUMBER=5432
      - DISCOURSE_POSTGRESQL_USERNAME=postgres
      - DISCOURSE_POSTGRESQL_PASSWORD=${POSTGRES_PW}
      - DISCOURSE_POSTGRESQL_NAME=openscp_forum
      - REDIS_HOST=redis
      - REDIS_PORT_NUMBER=6379
      - REDIS_PASSWORD=${REDIS_PW}