apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensdcp-forum-web-extensions
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi